#ifndef ERRORS_H
#define ERRORS_H

enum {SUCCESS, MEMORY_ALLOCATION_ERROR, FILE_NOT_EXISTS_ERROR, PARSING_INPUT_ERROR, 
	  ERR_LISTEN, ERR_ACCEPT, ERR_UNKNOWN, ERR_CHOICE, ERR_BIND, ERR_WRITE,
	  ERR_CREATE_SOCKET, ERR_CONNECT, ERR_TIMEOUT, ERR_SEND, ERR_OPTION, ERR_READ, ERR_PARSE};

int user_error(int err); 

#endif /* ERRORS_H */