#ifndef ERRORS_H
#define ERRORS_H

enum {SUCCESS, MEMORY_ALLOCATION_ERROR, FILE_NOT_EXISTS_ERROR, PARSING_INPUT_ERROR, ERR_LISTEN, ERR_ACCEPT, ERR_UNKNOWN, ERR_SOCKET_CREATION, ERR_CHOICE};

int error(int err); 

#endif /* ERRORS_H */