CC=gcc
HEADERS=headers
SRC=src
main: $(SRC)/menu_processor.c $(SRC)/main.c $(SRC)/dynamic_stack.c $(SRC)/list_stack.c $(SRC)/static_stack.c 
	$(CC) -o main -I$(HEADERS) $(SRC)/menu_processor.c $(SRC)/main.c $(SRC)/dynamic_stack.c $(SRC)/list_stack.c $(SRC)/static_stack.c

